djangopoc/core/urls.py
from django.urls import path
from .views import SignUpView, LoginView, LogoutView, home, home2, index, FarmerRegistrationView, InvestorRegistrationView, verify_email, resend_otp
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', index, name='index'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path("verify-email/<str:username>", verify_email, name="verify-email"),
    path("resend-otp", resend_otp, name="resend-otp"),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register_farmer/', FarmerRegistrationView.as_view(), name='register_farmer'),
    path('register_investor/', InvestorRegistrationView.as_view(), name='register_investor'),
    path('home/', home, name='home'),
    path('home2/', home2, name='home2'),
    # Add other URL patterns as needed
]

djangopoc/djangopoc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('farmer/', include('farmer.urls')),
    path('investor/', include('investor.urls')),
    path('superuser/', include('superuser.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

djangopoc/farmer/urls.py
from django.urls import path
from .views import home_farmer, notverified_farmer, farmer_profile, farmer_wallet, deposit_money, add_farmer_history, edit_farmer_history, add_ico_entity, ICOListView, ico_details_view, edit_ico_entity, FarmerEditView, ico_returns

app_name = 'farmer'

urlpatterns = [
    path('', home_farmer, name='home_farmer'),
    path('notverified', notverified_farmer, name='notverified_farmer'),
    path('profile/', farmer_profile, name='farmer_profile'),
    path('wallet/', farmer_wallet, name='farmer_wallet'),
    path('wallet_deposit/', deposit_money, name='deposit_money'),
    path('add_farmer_history/', add_farmer_history, name='add_farmer_history'),
    path('edit_farmer_history/<int:history_id>/', edit_farmer_history, name='edit_farmer_history'),
    path('add_ico_entity/', add_ico_entity, name='add_ico_entity'),
    path('show_farmer_icos/', ICOListView.as_view(), name='show_farmer_icos'),
    path('ico_details/<int:ico_id>/', ico_details_view, name='ico_details'),
    path('edit_ico_entity/<int:ico_id>/', edit_ico_entity, name='edit_ico_entity'),
    path('edit_farmer/', FarmerEditView.as_view(), name='edit_farmer'),
    path('ico_returns/<int:ico_id>/', ico_returns, name='ico_returns'),
    # Add other URL patterns as needed
]

djangopoc/farmer/models.py
from django.db import models
from django.utils import timezone
from core.models import Farmer
from datetime import timedelta
# Create your models here.

class FarmerHistory(models.Model):
    SEASON_CHOICES = [
        ('Rabi', 'Rabi'),
        ('Kharif', 'Kharif'),
    ]

    farmer = models.ForeignKey(Farmer, on_delete=models.CASCADE)
    season = models.CharField(max_length=6, choices=SEASON_CHOICES)
    year = models.IntegerField()
    crop = models.CharField(max_length=20)
    area_cultivated = models.FloatField()
    revenue = models.FloatField()
    expenses = models.FloatField()

    @property
    def percentage(self):
        # Calculate profit or loss percentage
        if self.revenue > self.expenses:
            return ((self.revenue - self.expenses) / self.expenses) * 100
        elif self.revenue < self.expenses:
            return -(((self.expenses - self.revenue) / self.expenses) * 100)
        else:
            return 0

    def __str__(self):
        return f"{self.farmer.user.username}'s History of {self.season}, {self.year}"


class ICOEntity(models.Model):
    farmer = models.ForeignKey(Farmer, on_delete=models.CASCADE)
    isVerified = models.BooleanField(default=False)
    is_rejected = models.BooleanField(default=False)
    is_return_provided = models.BooleanField(default=False)
    rejection_reason = models.TextField(blank=True, null=True)
    crop = models.CharField(max_length=20)
    land_area = models.FloatField()
    capital = models.FloatField()
    quantity = models.IntegerField()
    sold_quantity = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    closes_on = models.DateTimeField(null=True, blank=True)
    return_date = models.DateTimeField()

    @property
    def verified_and_active_entities(self):
        current_datetime = timezone.now()
        return ICOEntity.objects.filter(
            isVerified=True,
            closes_on__gte=current_datetime,
            sold_quantity__lt=models.F('quantity')
        ).order_by('closes_on')
    
    @property
    def stock_available(self):
        return self.quantity-self.sold_quantity
    
    @property
    def price(self):
        return float(self.capital)/float(self.quantity)
    
    @property
    def status(self):
        current_datetime = timezone.now()

        if not self.isVerified:
            return "Not Verified"
        elif current_datetime < self.closes_on:
            return "Open"
        elif current_datetime > self.return_date:
            return "Closed"
        elif self.closes_on <= current_datetime <= self.return_date:
            return "Pending"
        
    @property
    def open_return(self):
        current_datetime = timezone.now()
        return self.isVerified and current_datetime >= (self.return_date - timedelta(days=10))  and self.is_return_provided == False

    @property
    def is_remaining(self):
        current_datetime = timezone.now()
        return self.isVerified and current_datetime >= (self.return_date + timedelta(days=10))  and self.is_return_provided == False

    def __str__(self):
        return f"{self.farmer.user.username}'s ICOEntity - {self.crop}"

djangopoc/farmer/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator
from django.utils import timezone
from datetime import timedelta,datetime
from django.db.models import Sum, Q
from django.db import transaction
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse
from core.decorators import login_and_farmer_required, farmer_verified
from core.models import Farmer
from farmer.forms import FarmerHistoryForm, ICOEntityForm, ICOReturnsForm
from core.forms import FarmerRegistrationForm
from farmer.models import FarmerHistory, ICOEntity
from investor.models import ICOTransactions
from farmer.tasks import investor_return_email

# Create your views here.
@never_cache
@login_and_farmer_required
def home_farmer(request):
    return render(request, 'farmer/home_farmer.html', {'user': request.user})

@never_cache
@login_and_farmer_required
def notverified_farmer(request):
    return render(request, 'farmer/farmer_not_verified.html', {'user': request.user})

@never_cache
@login_and_farmer_required
def farmer_profile(request):
    farmer = Farmer.objects.get(user=request.user)
    context = {
        'user': request.user,
        'farmer': farmer,
    }
    return render(request, 'farmer/farmer_profile.html', context)

@never_cache
@farmer_verified
def farmer_wallet(request):
    farmer = Farmer.objects.get(user=request.user)
    farmer_wallet = farmer.wallet
    return render(request, 'farmer/farmer_wallet.html', {'wallet': farmer_wallet})

@never_cache
@farmer_verified
def deposit_money(request):
    farmer = Farmer.objects.get(user=request.user)
    farmer_wallet = farmer.wallet
    if request.method == 'POST':
        # print(type(request.POST['amount']))
        credit_card = request.POST.get('credit_card')
        cardholder_name = request.POST.get('cardholder_name')
        cvv = request.POST.get('cvv')
        expiration_date = request.POST.get('expiration_date')
        print('we got: ', credit_card, cardholder_name, cvv, expiration_date)

        #checks
        errors = {}
        if not is_valid_credit_card(credit_card):
            errors['credit_card'] = 'Invalid credit card number.'
        if not is_valid_expiration_date(expiration_date):
            errors['expiration_date'] = 'Invalid Exp. Date'
        
        if errors:
            form_data = {
                'credit_card': credit_card,
                'cardholder_name': cardholder_name,
                'cvv': cvv,
                'expiration_date': expiration_date,
                'amount': request.POST.get('amount'),
            }
            return render(request, 'farmer/deposit_money.html', {'errors': errors, 'form_data': form_data})

        # main functionality
        amount = float(request.POST.get('amount'))
        farmer_wallet.deposit(amount)
        return redirect(reverse('farmer:farmer_wallet'))
    return render(request, 'farmer/deposit_money.html')

def is_valid_credit_card(credit_card):
    card_number = int(credit_card)
    if card_number == 0: return False
    idx = 0
    total_sum = 0
    while card_number > 0:
        digit = card_number % 10
        if idx%2==1: 
            digit *= 2
            if digit >= 10:
                digit = digit % 10 + digit // 10
        total_sum += digit
        card_number //= 10
        idx += 1
    return bool(total_sum % 10 == 0 and len(credit_card) == 16 and credit_card.isdigit())


# def is_valid_cvv(cvv):
#     return len(cvv) == 3 and cvv.isdigit()

def is_valid_expiration_date(expiration_date):
    if len(expiration_date) != 5:
        return False
    if not expiration_date[:2].isdigit() or not expiration_date[3:].isdigit():
        return False
    month = int(expiration_date[:2])
    year = int(expiration_date[3:])
    if not 1 <= month <= 12:
        return False
    current_year = datetime.now().year % 100
    if year < current_year or (year == current_year and month < datetime.now().month):
        return False
    if year > current_year+10:
        return False
    return True

@never_cache
@login_and_farmer_required
def add_farmer_history(request):
    if request.method == 'POST':
        form = FarmerHistoryForm(request.POST)
        if form.is_valid():
            farmer = get_object_or_404(Farmer, user=request.user)
            area_cultivated = form.cleaned_data['area_cultivated']

             # Check if the sum of area_cultivated exceeds land_area
            total_area_cultivated = FarmerHistory.objects.filter(
                farmer=farmer,
                year=form.cleaned_data['year'],
                season=form.cleaned_data['season']
            ).aggregate(Sum('area_cultivated'))['area_cultivated__sum'] or 0.0

            # print('our total area: ', total_area_cultivated, type(total_area_cultivated))
            if total_area_cultivated + area_cultivated > farmer.land_area:
                form.add_error(None, 'Not enough land_area')
            else:
                history_entry = form.save(commit=False)
                history_entry.farmer = farmer
                history_entry.save()
                return redirect('farmer:farmer_profile')
    else:
        form = FarmerHistoryForm()
    

    return render(request, 'farmer/add_farmer_history.html', {'form': form})

@never_cache
@login_and_farmer_required
def edit_farmer_history(request, history_id):
    history_entry = get_object_or_404(FarmerHistory, id=history_id)
    if request.method == 'POST':
        form = FarmerHistoryForm(request.POST, instance=history_entry)
        if form.is_valid():
            farmer = get_object_or_404(Farmer, user=request.user)
            area_cultivated = form.cleaned_data['area_cultivated']

            # Check if the sum of area_cultivated exceeds land_area
            total_area_cultivated = FarmerHistory.objects.filter(
                farmer=farmer,
                year=form.cleaned_data['year'],
                season=form.cleaned_data['season']
            ).exclude(id=history_id).aggregate(Sum('area_cultivated'))['area_cultivated__sum'] or 0.0

            # print('our total area: ', total_area_cultivated, type(total_area_cultivated))
            # print('area cult: ', area_cultivated)
            # print('farmer area cult: ', farmer.land_area)
            # print(total_area_cultivated + area_cultivated > farmer.land_area)
            if total_area_cultivated + area_cultivated > farmer.land_area:
                form.add_error(None, 'Not enough land_area')
            else:
                form.save()
                return redirect('farmer:farmer_profile')
    else:
        form = FarmerHistoryForm(instance=history_entry)

    return render(request, 'farmer/edit_farmer_history.html', {'form': form, 'history_entry': history_entry})

@never_cache
@farmer_verified
def add_ico_entity(request):
    if request.method == 'POST':
        form = ICOEntityForm(request.POST)
        if form.is_valid():
            farmer = get_object_or_404(Farmer, user=request.user)
            new_entity_land_area = form.cleaned_data['land_area']
            capital = form.cleaned_data['capital'] 
            quantity = form.cleaned_data['quantity']
            cost = capital/quantity
            
            # Check if the total land_area of "Open" and "Pending" ICOEntities plus the new_entity_land_area exceeds farmer's land_area
            current_datetime = timezone.now()
            total_open_pending_land_area = ICOEntity.objects.filter(
                farmer=farmer,
                isVerified=True,
                created_at__lt=current_datetime,
                return_date__gt=current_datetime,
            ).aggregate(Sum('land_area'))['land_area__sum'] or 0
            print('already acquired: ' ,total_open_pending_land_area)
            print('price: ' , cost, type(cost))

            if new_entity_land_area + total_open_pending_land_area > farmer.land_area:
                form.add_error(None, 'Not enough land area')
            elif cost<50.0:
                form.add_error(None, 'Each share should cost > 50Rs')
            else:
                ico_entity = form.save(commit=False)
                ico_entity.farmer = farmer
                ico_entity.save()
                redirect_url = reverse('farmer:ico_details', kwargs={'ico_id': ico_entity.pk})
                return redirect(redirect_url)  # Adjust the redirect URL as needed
    else:
        form = ICOEntityForm()

    return render(request, 'farmer/create_ico.html', {'form': form})

# @never_cache
@method_decorator(farmer_verified, name='dispatch')
class ICOListView(View):
    template_name = 'farmer/show_farmer_icos.html'
    items_per_page = 5

    def get(self, request, *args, **kwargs):
        # Get user-selected filter from the query parameters
        filter_type = request.GET.get('filter', 'all')
        search_query = request.GET.get('search', '')

        current_datetime = timezone.now()

        # Apply filters based on the user's choice
        if filter_type == 'verified':
            icos = ICOEntity.objects.filter(farmer=request.user.farmer , isVerified=True)
        elif filter_type == 'not_verified':
            icos = ICOEntity.objects.filter(farmer=request.user.farmer, isVerified=False)
        elif filter_type == 'open':
            icos = ICOEntity.objects.filter(farmer=request.user.farmer, isVerified=True, closes_on__gte=current_datetime)
        elif filter_type == 'closed':
            icos = ICOEntity.objects.filter(farmer=request.user.farmer, isVerified=True, return_date__lt=current_datetime)
        elif filter_type == 'pending':
            icos = ICOEntity.objects.filter(
                farmer=request.user.farmer, 
                isVerified=True,
                closes_on__lte=current_datetime,
                return_date__gte=current_datetime
            )
        elif filter_type == 'rejected':

djangopoc/farmer/templates/farmer/create_ico.html
{% extends "base_farmer.html" %}

{% block content %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Update Farming History in your Profile Section!</strong> Remember to add your previous farming history for better performance and credibility of investors.
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="container p-2 rounded shadow-lg text-center fixed-length" style="max-width: 350px;">
    {% if form.non_field_errors %}
      {% for error in form.non_field_errors %}
        <div id="non-field-errors" class="alert alert-danger alert-dismissible fade show" role="alert">
          {{ error }}
          <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
    {% endif %}

    <h2 class="text-center">Create ICO</h2>
    <form action="{% url 'farmer:add_ico_entity' %}" method="post">
      {% csrf_token %}

      <div class="form-group {% if form.crop.errors %}has-error{% endif %} mb-2">
        {{ form.crop.label_tag }}
        {{ form.crop }}
        {% if form.crop.errors %}
          <div class="text-danger">
            {% for error in form.crop.errors %}
              {{ error }}
            {% endfor %}
          </div>
        {% endif %}
      </div>

      <div class="form-group {% if form.land_area.errors %}has-error{% endif %} mb-2">
        {{ form.land_area.label_tag }}
        {{ form.land_area }}
        {% if form.land_area.errors %}
          <div class="text-danger">
            {% for error in form.land_area.errors %}
              {{ error }}
            {% endfor %}
          </div>
        {% endif %}
      </div>

      <div class="form-group {% if form.capital.errors %}has-error{% endif %} mb-2">
        {{ form.capital.label_tag }}
        {{ form.capital }}
        {% if form.capital.errors %}
          <div class="text-danger">
            {% for error in form.capital.errors %}
              {{ error }}
            {% endfor %}
          </div>
        {% endif %}
      </div>

      <div class="form-group {% if form.quantity.errors %}has-error{% endif %} mb-2">
        {{ form.quantity.label_tag }}
        {{ form.quantity }}
        {% if form.quantity.errors %}
          <div class="text-danger">
            {% for error in form.quantity.errors %}
              {{ error }}
            {% endfor %}
          </div>
        {% endif %}
      </div>

      <div class="form-group {% if form.closes_on.errors %}has-error{% endif %} mb-2">
        {{ form.closes_on.label_tag }}
        {{ form.closes_on }}
        {% if form.closes_on.errors %}
          <div class="text-danger">
            {% for error in form.closes_on.errors %}
              {{ error }}
            {% endfor %}
          </div>
        {% endif %}
      </div>

      <div class="form-group {% if form.return_date.errors %}has-error{% endif %} mb-2">
        {{ form.return_date.label_tag }}
        {{ form.return_date }}
        {% if form.return_date.errors %}
          <div class="text-danger">
            {% for error in form.return_date.errors %}
              {{ error }}
            {% endfor %}
          </div>
        {% endif %}
      </div>

      <!-- Add other fields as needed -->

      <button type="submit" class="btn btn-success btn-block">Create</button>
    </form>
  </div>

  <script>
    document.addEventListener('DOMContentLoaded', function () {
        var today = new Date();
        var minDate = new Date(today);
        var maxDate = new Date(today);
        minDate.setDate(today.getDate()+10); // 10 days in future
        maxDate.setDate(today.getDate() + 20);  // 20 days in the future

        var closesOnInput = document.querySelector('#id_closes_on');
        closesOnInput.min = minDate.toISOString().split('T')[0];  // Set min attribute
        closesOnInput.max = maxDate.toISOString().split('T')[0];  // Set max attribute

        var minDate2 = new Date(today);
        var maxDate2 = new Date(today);
        minDate2.setDate(today.getDate()+90); // 90 days in future
        maxDate2.setDate(today.getDate() + 120);  // 120 days in the future
        var closesOnInput2 = document.querySelector('#id_return_date');
        closesOnInput2.min = minDate2.toISOString().split('T')[0];  // Set min attribute
        closesOnInput2.max = maxDate2.toISOString().split('T')[0];  // Set max attribute
    });
</script>
{% endblock %}

djangopoc/farmer/templates/farmer/edit_ico_entity.html
{% extends "base_farmer.html" %}

{% block content %}
    <div class="container rounded shadow-lg text-center fixed-length" style="max-width: 350px;">
        {% if form.non_field_errors %}
          {% for error in form.non_field_errors %}
            <div id="non-field-errors" class="alert alert-danger alert-dismissible fade show" role="alert">
              {{ error }}
              <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
        {% endif %}
        <h2 class="text-center">Edit ICO</h2>
        <form action="{% url 'farmer:edit_ico_entity' ico_entity.id %}" method="post">
            {% csrf_token %}

            <div class="form-group {% if form.crop.errors %}has-error{% endif %} mb-2">
                {{ form.crop.label_tag }}
                {{ form.crop }}
                {% if form.crop.errors %}
                    <div class="text-danger">
                        {% for error in form.crop.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <div class="form-group {% if form.land_area.errors %}has-error{% endif %} mb-2">
                {{ form.land_area.label_tag }}
                {{ form.land_area }}
                {% if form.land_area.errors %}
                    <div class="text-danger">
                        {% for error in form.land_area.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <div class="form-group {% if form.capital.errors %}has-error{% endif %} mb-2">
                {{ form.capital.label_tag }}
                {{ form.capital }}
                {% if form.capital.errors %}
                    <div class="text-danger">
                        {% for error in form.capital.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <div class="form-group {% if form.quantity.errors %}has-error{% endif %} mb-2">
                {{ form.quantity.label_tag }}
                {{ form.quantity }}
                {% if form.quantity.errors %}
                    <div class="text-danger">
                        {% for error in form.quantity.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <!-- <div class="form-group {% if form.closes_on.errors %}has-error{% endif %} mb-2">
                {{ form.closes_on.label_tag }}
                {{ form.closes_on }}
                {% if form.closes_on.errors %}
                    <div class="text-danger">
                        {% for error in form.closes_on.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <div class="form-group {% if form.return_date.errors %}has-error{% endif %} mb-2">
                {{ form.return_date.label_tag }}
                {{ form.return_date }}
                {% if form.return_date.errors %}
                    <div class="text-danger">
                        {% for error in form.return_date.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}
            </div> -->

            <div class="form-group {% if form.closes_on.errors %}has-error{% endif %} mb-2">
                {{ form.closes_on.label_tag }}
                <input type="date" class="form-control" id="id_closes_on" name="closes_on" value="{{ form.closes_on.value|date:'Y-m-d' }}">
                {% if form.closes_on.errors %}
                    <div class="text-danger">
                        {% for error in form.closes_on.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            
            <div class="form-group {% if form.return_date.errors %}has-error{% endif %} mb-2">
                {{ form.return_date.label_tag }}
                <input type="date" class="form-control" id="id_return_date" name="return_date" value="{{ form.return_date.value|date:'Y-m-d' }}">
                {% if form.return_date.errors %}
                    <div class="text-danger">
                        {% for error in form.return_date.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <!-- Add other fields as needed -->

            <button type="submit" class="btn btn-success btn-block">Update</button>
        </form>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var today = new Date();
            var minDate = new Date(today);
            var maxDate = new Date(today);
            minDate.setDate(today.getDate()+10); // 10 days in future
            maxDate.setDate(today.getDate() + 20);  // 20 days in the future
    
            var closesOnInput = document.querySelector('#id_closes_on');
            closesOnInput.min = minDate.toISOString().split('T')[0];  // Set min attribute
            closesOnInput.max = maxDate.toISOString().split('T')[0];  // Set max attribute
    
            var minDate2 = new Date(today);
            var maxDate2 = new Date(today);
            minDate2.setDate(today.getDate()+90); // 90 days in future
            maxDate2.setDate(today.getDate() + 120);  // 120 days in the future
            var closesOnInput2 = document.querySelector('#id_return_date');
            closesOnInput2.min = minDate2.toISOString().split('T')[0];  // Set min attribute
            closesOnInput2.max = maxDate2.toISOString().split('T')[0];  // Set max attribute
        });
    </script>
{% endblock %}

djangopoc/farmer/templates/farmer/farmer_profile.html
{% extends "base_farmer.html" %}
{% block content %}
  <!-- <div class="container d-flex flex-column align-items-center justify-content-center">
    {{ user.first_name }} {{ user.last_name }}  <br>
    Aadhar Number: {{ farmer.aadhar_number }}  <br>
    PAN Number: {{ farmer.pan_number }}
    <br>
    Land Area: {{ farmer.land_area }}
  </div> -->
  <div class="container mt-5 rounded shadow-lg text-center fixed-length">

    {% if farmer.is_rejected%}
        <div class="alert alert-danger mt-3 mb-2 text-center" role="alert">
            Your Profile got rejected! Reason: {{ farmer.rejection_reason }}
         </div>
         <div class="text-center">
              <a href="{% url 'farmer:edit_farmer'%}" class="btn btn-warning mt-1">Update Profile</a>
         </div>
    {% endif %}

    <div class="row p-3 mt-3">
        <div class="col-md-6 mx-auto card shadow-lg">
            <h1 class="text-center">{{ user.first_name|capfirst }} {{ user.last_name|capfirst }}</h1>
            <p class="text-center"><b>UserName:</b> {{ user.username }}</p>
            <p class="text-center"><b>Email:</b> {{ user.email }}</p>
            <p class="text-center"><b>Contact No:</b> {{ user.phone }}</p>
            <p class="text-center"><b>Aadhar No:</b> {{ farmer.aadhar_number }}</p>
            <p class="text-center"><b>PAN No:</b> {{ farmer.pan_number }}</p>
            <p class="text-center"><b>Land Area:</b> {{ farmer.land_area }} sq. meters</p>
            <p class="text-center"><b>Documents:</b> <a href="{{farmer.documents.url}}" target="_blank">view documents</a></p>
        </div>
    </div>

    <!-- Add button to add FarmerHistory entry -->
    <div class="row mt-3 mb-3">
        <div class="col-md-6 mx-auto">
            <a class="btn btn-success btn-lg btn-block" href="{% url 'farmer:add_farmer_history' %}">Add Farmer History Entry</a>
        </div>
    </div>

    <!-- Display FarmerHistory entries in a table with Edit buttons -->
    {% if farmer.farmerhistory_set.all %}
    <div class="row mt-3">
        <div class="col-md-8 mx-auto">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Season</th>
                        <th>Year</th>
                        <th>Crop</th>
                        <th>Area Cultivated(sq. meters)</th>
                        <th>Revenue(&#8377;)</th>
                        <th>Expenses(&#8377;)</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for history_entry in farmer.farmerhistory_set.all %}
                        <tr>
                            <td>{{ history_entry.season }}</td>
                            <td>{{ history_entry.year }}</td>
                            <td>{{ history_entry.crop }}</td>
                            <td>{{ history_entry.area_cultivated }}</td>
                            <td>{{ history_entry.revenue }}</td>
                            <td>{{ history_entry.expenses }}</td>
                            <td>
                                <a class="btn btn-warning btn-sm" href="{% url 'farmer:edit_farmer_history' history_entry.id %}">Edit</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}

djangopoc/farmer/templates/farmer/farmer_wallet.html
{% extends "base_farmer.html" %}
{% block content %}
<div class="container">
    <div class="card shadow-lg mx-auto" style="max-width: 350px;">
        <!-- <img src="https://media.gettyimages.com/id/912819642/vector/wallet-flat-design-e-commerce-icon.jpg?s=612x612&w=0&k=20&c=jUT9SJ5wZF1ULax2Gk_s_3GZZAYvCm9SBfHahoaZUg4=" alt="Logo" class="card-img-top"> -->
        <div class="card-body text-center">
            <!-- <h5 class="card-title display-3">Wallet</h5> -->
            <h2 class="card-title">Wallet</h2>
            <img src="https://media.gettyimages.com/id/912819642/vector/wallet-flat-design-e-commerce-icon.jpg?s=612x612&w=0&k=20&c=jUT9SJ5wZF1ULax2Gk_s_3GZZAYvCm9SBfHahoaZUg4=" alt="Logo" class="img-fluid rounded-circle">
            <p class="card-text lead">Your wallet balance is &#8377;{{ wallet.balance|floatformat:2 }}</p>
            <p><a class="btn btn-warning" href="{% url 'farmer:deposit_money' %}">Add Money</a></p>
        </div>
    </div>
</div>
{% endblock %}