djangopoc/core/urls.py
from django.urls import path
from .views import SignUpView, LoginView, LogoutView, home, home2, index, FarmerRegistrationView, InvestorRegistrationView, verify_email, resend_otp
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', index, name='index'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path("verify-email/<str:username>", verify_email, name="verify-email"),
    path("resend-otp", resend_otp, name="resend-otp"),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register_farmer/', FarmerRegistrationView.as_view(), name='register_farmer'),
    path('register_investor/', InvestorRegistrationView.as_view(), name='register_investor'),
    path('home/', home, name='home'),
    path('home2/', home2, name='home2'),
    # Add other URL patterns as needed
]

djangopoc/djangopoc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('farmer/', include('farmer.urls')),
    path('investor/', include('investor.urls')),
    path('superuser/', include('superuser.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

djangopoc/investor/urls.py
from django.urls import path
from .views import home_investor, notverified_investor, investor_profile, investor_wallet, deposit_money, InvestorICOListView, buy_ico, investor_icos, ico_details, InvestorEditView

app_name = 'investor'

urlpatterns = [
    path('', home_investor, name='home_investor'),
    path('notverified', notverified_investor, name='notverified_investor'),
    path('profile/', investor_profile, name='investor_profile'),
    path('wallet/', investor_wallet, name='investor_wallet'),
    path('wallet_deposit/', deposit_money, name='deposit_money'),
    path('show_icos/', InvestorICOListView.as_view(), name='show_icos'),
    path('buy_ico/<int:ico_id>/', buy_ico, name='buy_ico'),
    path('investor_icos/', investor_icos, name='investor_icos'),
    path('ico_details/<int:ico_id>/', ico_details, name='ico_details'),
    path('edit_investor/', InvestorEditView.as_view(), name='edit_investor'),
    # Add other URL patterns as needed
]

djangopoc/investor/models.py
from django.db import models
from farmer.models import ICOEntity
from core.models import Investor

# Create your models here.
class ICOTransactions(models.Model):
    ico = models.ForeignKey(ICOEntity, on_delete=models.CASCADE)
    investor = models.ForeignKey(Investor, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    per_entity_cost = models.DecimalField(max_digits=10, decimal_places=2)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Transaction {self.pk} - {self.investor} ({self.quantity} units)"

    class Meta:
        verbose_name_plural = "ICO Transactions"

djangopoc/investor/forms.py
from django import forms

class BuyICOForm(forms.Form):
    quantity = forms.IntegerField(min_value=1)

djangopoc/investor/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from datetime import timedelta,datetime
from django.views import View
from django.views.decorators.cache import never_cache
from django.contrib import messages
from django.db import transaction
from django.db.models import Q, F, ExpressionWrapper, FloatField
from djangopoc import settings
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.decorators import method_decorator
from core.decorators import login_and_investor_required, investor_verified
from core.models import Investor
from farmer.models import ICOEntity, FarmerHistory
from investor.models import ICOTransactions
from investor.forms import BuyICOForm
from core.forms import InvestorRegistrationForm
from investor.tasks import test_func, send_purchase_confirmation_email


# Create your views here.

# def send_purchase_confirmation_email(investor, quantity, total_cost, ico_entity):
#     subject = 'ICO Purchase Confirmation'
#     message = f'Thank you {investor.user.first_name} for purchasing {quantity} units of Farmer {ico_entity.farmer.user.first_name}\'s {ico_entity.crop} crop ICO having id: {ico_entity.id}. You successfully paid {total_cost} Rs.'
#     from_email = settings.EMAIL_HOST_USER
#     recipient_list = [investor.user.email]
#     print( subject, message, from_email, recipient_list)

#     send_mail(subject, message, from_email, recipient_list, fail_silently=True)

@never_cache
@login_and_investor_required
def home_investor(request):
    # print(request.user.first_name, request.user.email, 12)
    # test_func.delay(request.user.first_name, request.user.email, 12)
    return render(request, 'investor/home_investor.html', {'user': request.user})

@never_cache
@login_and_investor_required
def notverified_investor(request):
    return render(request, 'investor/investor_not_verified.html', {'user': request.user})

@never_cache
@login_and_investor_required
def investor_profile(request):
    investor = Investor.objects.get(user=request.user)
    context = {
        'user': request.user,
        'investor': investor,
    }
    return render(request, 'investor/investor_profile.html', context)

@never_cache
@investor_verified
def investor_wallet(request):
    investor = Investor.objects.get(user=request.user)
    investor_wallet = investor.wallet
    return render(request, 'investor/investor_wallet.html', {'wallet': investor_wallet})

@never_cache
@investor_verified
def deposit_money(request):
    investor = Investor.objects.get(user=request.user)
    investor_wallet = investor.wallet
    if request.method == 'POST':
        # print(type(request.POST['amount']))
        credit_card = request.POST.get('credit_card')
        cardholder_name = request.POST.get('cardholder_name')
        cvv = request.POST.get('cvv')
        expiration_date = request.POST.get('expiration_date')
        print('we got: ', credit_card, cardholder_name, cvv, expiration_date)

        # checks
        errors = {}
        if not is_valid_credit_card(credit_card):
            errors['credit_card'] = 'Invalid credit card number.'
        if not is_valid_expiration_date(expiration_date):
            errors['expiration_date'] = 'Invalid Exp. Date'
        
        if errors:
            form_data = {
                'credit_card': credit_card,
                'cardholder_name': cardholder_name,
                'cvv': cvv,
                'expiration_date': expiration_date,
                'amount': request.POST.get('amount'),
            }
            return render(request, 'investor/deposit_money.html', {'errors': errors, 'form_data': form_data})
        # main functionality
        amount = float(request.POST.get('amount'))
        # print('will work!')
        investor_wallet.deposit(amount)
        return redirect(reverse('investor:investor_wallet'))
    return render(request, 'investor/deposit_money.html')

def is_valid_credit_card(credit_card):
    card_number = int(credit_card)
    if card_number == 0: return False
    idx = 0
    total_sum = 0
    while card_number > 0:
        digit = card_number % 10
        if idx%2==1: 
            digit *= 2
            if digit >= 10:
                digit = digit % 10 + digit // 10
        total_sum += digit
        card_number //= 10
        idx += 1
    return bool(total_sum % 10 == 0 and len(credit_card) == 16 and credit_card.isdigit())


# def is_valid_cvv(cvv):
#     return len(cvv) == 3 and cvv.isdigit()

def is_valid_expiration_date(expiration_date):
    if len(expiration_date) != 5:
        return False
    if not expiration_date[:2].isdigit() or not expiration_date[3:].isdigit():
        return False
    month = int(expiration_date[:2])
    year = int(expiration_date[3:])
    if not 1 <= month <= 12:
        return False
    current_year = datetime.now().year % 100
    if year < current_year or (year == current_year and month < datetime.now().month):
        return False
    if year > current_year+10:
        return False
    return True


# @never_cache
@method_decorator(login_and_investor_required, name='dispatch')
class InvestorICOListView(View):
    template_name = 'investor/show_icos.html'
    items_per_page = 5

    def get(self, request, *args, **kwargs):
        # Get all verified and active ICOs
        search_query = request.GET.get('search', '')
        icos = ICOEntity().verified_and_active_entities

        # Apply filter based on form inputs
        crop_name = request.GET.get('crop_name', '')
        farmer_name = request.GET.get('farmer_name', '')
        max_price = request.GET.get('max_price', '')
        # min_price = request.GET.get('min_price', '')
        close_date = request.GET.get('close_date', '')
        return_date = request.GET.get('return_date', '')
        # print('we have' ,max_price, type(max_price))

        if crop_name:
            icos = icos.filter(crop__icontains=crop_name)
        if farmer_name:
            icos = icos.filter(farmer__user__first_name__icontains=farmer_name)
        if max_price:
            icos = icos = icos.annotate(
                calculated_price=ExpressionWrapper(F('capital') / F('quantity'), output_field=FloatField())
            ).filter(calculated_price__lte=max_price)
        # if min_price:
        #     icos = icos.annotate(
        #         calculated_price=ExpressionWrapper(F('capital') / F('quantity'), output_field=FloatField())
        #     ).filter(calculated_price__gte=min_price)
        if close_date:
            try: 
                close_date = timezone.datetime.strptime(close_date, '%Y-%m-%d')
                # Set the time to just a minute before midnight
                close_date = close_date.replace(hour=23, minute=59, second=59)
                # Make close_date timezone-aware
                close_date = timezone.make_aware(close_date)
                # print('now it is: ', close_date, type(close_date))
                icos = icos.filter(closes_on__lte=close_date)
            except ValueError:
                # Handle the case where the close_date string is not a valid date
                print('Invalid date format')
        if return_date:
            try: 
                return_date = timezone.datetime.strptime(return_date, '%Y-%m-%d')
                # Set the time to just a minute before midnight
                return_date = return_date.replace(hour=23, minute=59, second=59)
                # Make close_date timezone-aware
                return_date = timezone.make_aware(return_date)
                # print('now it is: ', close_date, type(close_date))
                icos = icos.filter(return_date__lte=return_date)
            except ValueError:
                # Handle the case where the close_date string is not a valid date
                print('Invalid date format')


        # Apply search filter if search_query is present
        if search_query:
            icos = icos.filter(
                Q(crop__icontains=search_query) | Q(farmer__user__first_name__icontains=search_query) | Q(farmer__user__username__icontains=search_query)
            )

        paginator = Paginator(icos, self.items_per_page)
        page = request.GET.get('page')

        try:
            icos = paginator.page(page)
        except PageNotAnInteger:
            # If the page parameter is not an integer, deliver the first page.
            icos = paginator.page(1)
        except EmptyPage:
            # If the page is out of range (e.g., 9999), deliver the last page.
            icos = paginator.page(paginator.num_pages)

        context = {'icos': icos}
        return render(request, self.template_name, context)

@never_cache    
@investor_verified
def buy_ico(request, ico_id):
    investor = get_object_or_404(Investor, user=request.user)
    ico_entity = get_object_or_404(ICOEntity, pk=ico_id)

    form = BuyICOForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        quantity = form.cleaned_data['quantity']

        with transaction.atomic():
            
            ico_entity = ICOEntity.objects.select_for_update().get(pk=ico_entity.pk)

            if quantity > 0 and quantity <= ico_entity.stock_available:
                total_cost = ico_entity.price * quantity
                print('Total cost: ', total_cost)

                if investor.wallet.balance >= total_cost:

                    # Check if there's an existing transaction
                    existing_transaction = ICOTransactions.objects.filter(
                        ico=ico_entity,
                        investor=investor
                    ).first()

                    if existing_transaction:
                        # Update the existing transaction's quantity
                        existing_transaction.quantity += quantity
                        existing_transaction.save()
                    else:

djangopoc/investor/templates/investor/buy_ico.html
{% extends "base_investor.html" %}
{% block content %}
    <div class="container rounded shadow-lg text-center fixed-length" style="max-width: 350px;">
        {% if form.non_field_errors %}
            <div id="non-field-errors" class="alert alert-danger alert-dismissible fade show" role="alert">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
                <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}

        <h2 class="text-center">Buy ICO</h2>
        <input type="hidden" id="ico_price" value="{{ ico_entity.price }}">
        <input type="hidden" id="total-cost" name="total_cost" value="">
        <p style="color: green;">Cost: <span id="place_it">0.00</span> Rs</p>
        
        <form method="post" action="{% url 'investor:buy_ico' ico_entity.id %}">
            {% csrf_token %}
            
            <div class="form-group {% if form.quantity.errors %}has-error{% endif %} mb-2">
                <label for="{{ form.quantity.id_for_label }}">Quantity:</label>
                {{ form.quantity }}
                {% if form.quantity.errors %}
                    <div class="text-danger">
                        {% for error in form.quantity.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        
            <!-- Add other fields as needed -->
        
            <button type="submit" class="btn btn-primary btn-block mb-2">Buy ICO</button>
        </form>        
    </div>

<script>

// document.addEventListener('DOMContentLoaded', function () {
//     const quantityInput = document.getElementById('id_quantity');
    
//     if (quantityInput !== null) {
//         quantityInput.addEventListener('keyup', () => calculateTotalCost());
//         quantityInput.addEventListener('load', () => calculateTotalCost());
//         function calculateTotalCost() {
//             let quantity = Number(document.getElementById('id_quantity').value);
//             let icoPrice = parseFloat(document.getElementById('ico_price').value);
//             // console.log('price', icoPrice, quantity);
//             let totalCost = quantity * icoPrice;

//             // console.log(totalCost);
//             // Update the total cost display
//             let formattedTotalCost = totalCost.toFixed(2);
//             document.getElementById('place_it').textContent = formattedTotalCost;
//         }
//     } else {
//         console.error('Quantity input field not found');
//     }
// });

window.addEventListener('load', () => {
    const quantityInput = document.getElementById('id_quantity');
    const icoPriceElement = document.getElementById('ico_price');
    const totalCostDisplay = document.getElementById('place_it');

    if (quantityInput && icoPriceElement && totalCostDisplay) {
        // Attach a single 'keyup' event listener:
        quantityInput.addEventListener('keyup', calculateTotalCost);

        // Trigger calculation on initial load:
        calculateTotalCost();

        function calculateTotalCost() {
            const quantity = Number(quantityInput.value);
            const icoPrice = parseFloat(icoPriceElement.value);
            const totalCost = quantity * icoPrice;
            const formattedTotalCost = totalCost.toFixed(2);

            totalCostDisplay.textContent = formattedTotalCost;
        }
    } else {
        console.error('One or more required elements not found');
    }
});
</script>
{% endblock %}

djangopoc/investor/templates/investor/deposit_money.html
{% extends "base_investor.html" %}
{% block content %}
<div class="container">
    <div class="card shadow-lg mx-auto" style="max-width: 350px;">
        <div class="card-body text-center">
            <h2 class="card-title">Add Money</h2>
            <!-- <img src="https://media.gettyimages.com/id/912819642/vector/wallet-flat-design-e-commerce-icon.jpg?s=612x612&w=0&k=20&c=jUT9SJ5wZF1ULax2Gk_s_3GZZAYvCm9SBfHahoaZUg4=" alt="Logo" class="img-fluid rounded-circle"> -->
            <form action="{% url 'investor:deposit_money' %}" method="post">
                {% csrf_token %}
                 <!-- First Row -->
                 <div class="form-group mb-2">
                    <label for="credit_card">Credit Card Number:</label>
                    <input type="text" class="form-control" name="credit_card" placeholder="XXXX XXXX XXXX XXXX" autocomplete="off" size="16" maxlength="16" minlength="16" pattern="[0-9]{16}" title="Enter a valid 16-digit credit card number" required value="{{ form_data.credit_card }}">
                    {% if errors.credit_card %}
                        <div class="text-danger">{{ errors.credit_card }}</div>
                    {% endif %}
                </div>
                <div class="form-group mb-2">
                    <label for="cardholder_name">Cardholder Name:</label>
                    <input type="text" class="form-control" name="cardholder_name" placeholder="Cardholder Name" autocomplete="off" maxlength="255" title="Enter a valid cardholder name" pattern="^[a-zA-Z]+([ ][a-zA-Z]+)*$" required value="{{ form_data.cardholder_name }}">
                </div>

                <!-- Second Row -->
                <div class="form-group mb-2 row">
                    <div class="col-6">
                        <label for="cvv">CVV:</label>
                        <input type="password" class="form-control" name="cvv" placeholder="CVV" size="3" maxlength="3" minlength="3" autocomplete="off" pattern="[0-9]{3}" title="Enter a valid 3-digit CVV" required value="{{ form_data.cvv }}">
                    </div>
                    <div class="col-6">
                        <label for="expiration_date">Expiration Date:</label>
                        <input type="text" class="form-control" name="expiration_date" placeholder="MM/YY" autocomplete="off" pattern="([0-9]{2})/([0-9]{2})" title="Enter a valid MM/YY format" required value="{{ form_data.expiration_date }}">
                        {% if errors.expiration_date %}
                            <div class="text-danger">{{ errors.expiration_date }}</div>
                        {% endif %}
                    </div>
                </div>
                 <div class="form-group mb-2">
                   <label for="amount">Amount:</label>
                   <input type="number" class="form-control" name="amount" min="1" autocomplete="off" title="Enter an amount greater than or equal to 0" pattern="[0-9]" required value="{{ form_data.amount }}">
                 </div>
                 <button type="submit" class="btn btn-success">Add</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

djangopoc/investor/templates/investor/investor_icos.html
{% extends "base_investor.html" %}
{% block content %}
    <div class="container">
        <!-- <h2>ICOs for {{ investor.user.username }}</h2> -->
        <form method="get" action="{% url 'investor:investor_icos' %}" class="mb-4">
            <div class="row">
              <div class="col-md-8">
                <!-- <label for="filter" class="form-label">Filter by:</label> -->
                <select name="filter" id="filter" class="form-select">
                  <option value="all" {% if filter_type == 'all' %}selected{% endif %}>All</option>
                  <option value="open" {% if filter_type == 'open' %}selected{% endif %}>Open</option>
                  <option value="closed" {% if filter_type == 'closed' %}selected{% endif %}>Closed</option>
                  <option value="pending" {% if filter_type == 'pending' %}selected{% endif %}>Pending</option>
                </select>
              </div>
              <div class="col-md-4">
                <button type="submit" class="btn btn-secondary">Apply Filter</button>
              </div>
            </div>
          </form>

        {% if transactions %}
                {% for transaction in transactions %}
                    <!-- <tr>
                        <td>{{ transaction.pk }}</td>
                        <td>{{ transaction.ico.crop }}</td>
                        <td>{{ transaction.quantity }}</td>
                        <td>{{ transaction.per_entity_cost }}</td>
                        <td>{{ transaction.updated_at }}</td>
                    </tr> -->
                    <div class="card mb-3">
                        <div class="row ">
                            <div class="col-md-4">
                                <img src="https://images.unsplash.com/photo-1564417947365-8dbc9d0e718e?w=200&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y3JvcHxlbnwwfHwwfHx8MA%3D%3D" class="card-img-top" alt="crop" style="width: px; height: 200px; object-fit: cover;">
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h4 class="card-title">{{ transaction.ico.crop }}</h4>
                                    <div class="row">
                                        <div class="col-md-6 card-text">
                                            <strong>Quantity: </strong>{{ transaction.quantity }}<br>
                                            <strong>Price: </strong>{{ transaction.per_entity_cost }} Rs<br>
                                            <strong>Status: </strong>{{ transaction.ico.status }}
                                        </div>
                                        <div class="col-md-6 card-text">
                                            <strong>Farmer Name: </strong>{{ transaction.ico.farmer.user.first_name }}<br>
                                            <strong>Return Date: </strong>{{ transaction.ico.return_date|date:"Y-m-d" }} 
                                            <!-- Add more attributes here -->
                                        </div>
                                    </div>
                                    <!-- <a href="#" class="btn btn-primary mt-3">Show Details</a> -->
                                    <div class="row">
                                        <div class="col-md-6"><a href="{% url 'investor:ico_details' transaction.ico.id %}" class="btn btn-success mt-3">Show Details</a></div>
                                        {% if transaction.ico.status == "Open" and transaction.ico.stock_available > 0 %}
                                            <div class="col-md-6"><a href="{% url 'investor:buy_ico' transaction.ico.id %}" class="btn btn-warning mt-3">Buy More</a></div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                    </div>
                    </div>
                {% endfor %}
                <!-- Pagination links -->
                <div class="pagination mt-3" style="justify-content: center;">
                    <span class="step-links">
                        {% if transactions.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ transactions.previous_page_number }}">previous</a>
                        {% endif %}
                    
                        <span class="current">
                            Page {{ transactions.number }} of {{ transactions.paginator.num_pages }}.
                        </span>
                    
                        {% if transactions.has_next %}
                            <a href="?page={{ transactions.next_page_number }}">next</a>
                            <a href="?page={{ transactions.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
        {% else %}
            <div class="alert alert-info mt-3 text-center" role="alert">
                No ICOs found for {{ investor.user.username }}!
            </div>
        {% endif %}
    </div>
{% endblock %}

djangopoc/investor/templates/investor/show_icos.html
{% extends "base_investor.html" %}
{% block content %}
  <div class="container mt-3">
    <div class="row">
    <div class="col-md-3 shadow-md rounded bg-light" style="max-height: 420px;">
        <div class="row mt-3 mb-3">
             <!-- Filter Form -->
        <form method="get" action="{% url 'investor:show_icos' %}" class="mb-3">
            <div class="mb-2">
              <label for="crop_name">Crop Name:</label>
              <input type="text" name="crop_name" class="form-control" id="crop_name" value="{{ request.GET.crop_name }}">
            </div>
            <div class="mb-2">
                <label for="farmer_name">Farmer Name:</label>
                <input type="text" name="farmer_name" class="form-control" id="farmer_name" value="{{ request.GET.farmer_name }}">
              </div>
            <div class="mb-2">
              <label for="max_price">Max Price:</label>
              <input type="number" name="max_price" class="form-control" id="max_price" value="{{ request.GET.max_price }}" min="50">
            </div>
            <!-- <div class="mb-2">
              <label for="min_price">Min Price:</label>
              <input type="number" name="min_price" class="form-control" id="min_price" value="{{ request.GET.min_price }}" min="1">
            </div> -->
            <div class="mb-2">
              <label for="close_date">Closes By:</label>
              <input type="date" name="close_date" class="form-control" id="close_date" value="{{ request.GET.close_date }}">
            </div>
            <div class="mb-2">
                <label for="return_date">Return By:</label>
                <input type="date" name="return_date" class="form-control" id="return_date" value="{{ request.GET.return_date }}">
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-secondary">Apply Filter</button>
            </div>
          </form>
        </div>
    </div>
    <div class="col-md-9">
    {% if icos %}
    {% for ico in icos %}
      <div class="card mb-4">
        <div class="row ">
            <div class="col-md-4">
                <img src="https://images.unsplash.com/photo-1564417947365-8dbc9d0e718e?w=200&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y3JvcHxlbnwwfHwwfHx8MA%3D%3D" class="card-img-top" alt="crop" style="width: px; height: 200px; object-fit: cover;">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h4 class="card-title">{{ ico.crop }}</h4>
                    <div class="row">
                        <div class="col-md-6 card-text">
                            <strong>Price: </strong>{{ ico.price|floatformat:2 }} &#8377;<br>
                            <strong>Closes On: </strong>{{ ico.closes_on|date:"Y-m-d" }}<br>
                            <strong>Farmer Name: </strong>{{ ico.farmer.user.first_name }}
                        </div>
                        <div class="col-md-6 card-text">
                            <strong>Stocks Available: </strong>{{ ico.stock_available }}<br>
                            <strong>Return Date: </strong>{{ ico.return_date|date:"Y-m-d" }} 
                            <!-- Add more attributes here -->
                        </div>
                    </div>
                    <!-- <a href="#" class="btn btn-primary mt-3">Show Details</a> -->
                    <!-- Pass the ICO details directly to the details template using the URL -->
                    <div class="row">
                        <div class="col-md-6"><a href="{% url 'investor:ico_details' ico.id %}" class="btn btn-success mt-3">Show Details</a></div>
                        <div class="col-md-6"><a href="{% url 'investor:buy_ico' ico.id %}" class="btn btn-warning mt-3">Buy ICO</a></div>
                    </div>
                </div>
            </div>
    </div>
    </div>
    {% endfor %}
    <!-- Pagination links -->
    <div class="pagination mt-3" style="justify-content: center;">
        <span class="step-links">
            {% if icos.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ icos.previous_page_number }}">previous</a>
            {% endif %}
        
            <span class="current">
                Page {{ icos.number }} of {{ icos.paginator.num_pages }}.
            </span>
          
            {% if icos.has_next %}
                <a href="?page={{ icos.next_page_number }}">next</a>
                <a href="?page={{ icos.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
      </div>
    {% else %}
    <div class="alert alert-info mt-3 text-center" role="alert">
        No such ICOs found!
    </div>
    {% endif %}
    </div>
    </div>

  </div>
  <script>
    document.addEventListener('DOMContentLoaded', function () {
        var today = new Date();
        var minDate = new Date(today);
        var maxDate = new Date(today);
        minDate.setDate(today.getDate()); // 10 days in future
        maxDate.setDate(today.getDate() + 20);  // 20 days in the future

        var closesOnInput = document.querySelector('#close_date');
        closesOnInput.min = minDate.toISOString().split('T')[0];  // Set min attribute
        closesOnInput.max = maxDate.toISOString().split('T')[0];  // Set max attribute

        var minDate2 = new Date(today);
        var maxDate2 = new Date(today);
        minDate2.setDate(today.getDate()+30); // 90 days in future
        maxDate2.setDate(today.getDate() + 120);  // 120 days in the future
        var closesOnInput2 = document.querySelector('#return_date');
        closesOnInput2.min = minDate2.toISOString().split('T')[0];  // Set min attribute
        closesOnInput2.max = maxDate2.toISOString().split('T')[0];  // Set max attribute
    });
</script>
{% endblock %}