djangopoc/core/urls.py
from django.urls import path
from .views import SignUpView, LoginView, LogoutView, home, home2, index, FarmerRegistrationView, InvestorRegistrationView, verify_email, resend_otp
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', index, name='index'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path("verify-email/<str:username>", verify_email, name="verify-email"),
    path("resend-otp", resend_otp, name="resend-otp"),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register_farmer/', FarmerRegistrationView.as_view(), name='register_farmer'),
    path('register_investor/', InvestorRegistrationView.as_view(), name='register_investor'),
    path('home/', home, name='home'),
    path('home2/', home2, name='home2'),
    # Add other URL patterns as needed
]

djangopoc/djangopoc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('farmer/', include('farmer.urls')),
    path('investor/', include('investor.urls')),
    path('superuser/', include('superuser.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

djangopoc/superuser/urls.py
from django.urls import path
from superuser.views import home_superuser, show_icos, superuser_profile, ico_details, approve_ico, reject_ico, show_farmers, farmer_details, approve_farmer, reject_farmer, show_investors, investor_details, approve_investor, reject_investor, force_ico_returns

app_name = 'superuser'

urlpatterns = [
    path('', home_superuser, name='home_superuser'),
    path('profile/', superuser_profile, name='superuser_profile'),
    path('show_icos/', show_icos, name='show_icos'),
    path('ico_details/<int:ico_id>/', ico_details, name='ico_details'),
    path('approve_ico/<int:ico_id>/', approve_ico, name='approve_ico'),
    path('reject_ico/<int:ico_id>/', reject_ico, name='reject_ico'),
    path('force_ico_returns/<int:ico_id>/', force_ico_returns, name='force_ico_returns'),
    path('show_farmers/', show_farmers, name='show_farmers'),
    path('farmer_details/<int:user_id>/', farmer_details, name='farmer_details'),
    path('approve_farmer/<int:user_id>/', approve_farmer, name='approve_farmer'),
    path('reject_farmer/<int:user_id>/', reject_farmer, name='reject_farmer'),
    path('show_investors/', show_investors, name='show_investors'),
    path('investor_details/<int:user_id>/', investor_details, name='investor_details'),
    path('approve_investor/<int:user_id>/', approve_investor, name='approve_investor'),
    path('reject_investor/<int:user_id>/', reject_investor, name='reject_investor'),
]

djangopoc/superuser/models.py
from django.db import models

# Create your models here.

djangopoc/superuser/forms.py
from django import forms
from farmer.models import ICOEntity
from core.models import Farmer, Investor

class ICORejectionForm(forms.ModelForm):
    class Meta:
        model = ICOEntity
        fields = ['rejection_reason']
        widgets = {
            'rejection_reason': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
        }

    def clean_rejection_reason(self):
        rejection_reason = self.cleaned_data.get('rejection_reason')

        if not rejection_reason.strip():
            raise forms.ValidationError("Please provide a rejection reason when rejecting an ICO.")
        
        return rejection_reason
    
class FarmerRejectionForm(forms.ModelForm):
    class Meta:
        model = Farmer
        fields = ['rejection_reason']
        widgets = {
            'rejection_reason': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
        }

    def clean_rejection_reason(self):
        rejection_reason = self.cleaned_data.get('rejection_reason')

        if not rejection_reason.strip():
            raise forms.ValidationError("Please provide a rejection reason when rejecting an Farmer.")
        
        return rejection_reason
    

class InvestorRejectionForm(forms.ModelForm):
    class Meta:
        model = Farmer
        fields = ['rejection_reason']
        widgets = {
            'rejection_reason': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
        }

    def clean_rejection_reason(self):
        rejection_reason = self.cleaned_data.get('rejection_reason')

        if not rejection_reason.strip():
            raise forms.ValidationError("Please provide a rejection reason when rejecting an Investor.")
        
        return rejection_reason

djangopoc/superuser/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q, Sum
from django.db import transaction
from django.views.decorators.cache import never_cache
from django.urls import reverse
from core.decorators import login_and_user_type_required
from farmer.models import ICOEntity, FarmerHistory
from investor.models import ICOTransactions
from core.models import Farmer, Investor
from superuser.tasks import broadcast_newico_email, farmer_verified_email, investor_verified_email, investor_forced_return_email, ico_rejection_email, farmer_rejection_email, investor_rejection_email
from superuser.forms import ICORejectionForm, FarmerRejectionForm, InvestorRejectionForm
from datetime import timedelta

# Create your views here.
@never_cache
@login_and_user_type_required('S')
def home_superuser(request):
    # return HttpResponse('Bello SuperUser')
    return render(request, 'superuser/home_superuser.html', {'user': request.user})

@never_cache
@login_and_user_type_required('S')
def superuser_profile(request):
    context = {
        'user': request.user,
    }
    return render(request, 'superuser/superuser_profile.html', context)


#ICO related views here:
@never_cache
@login_and_user_type_required('S')
def show_icos(request):
    current_datetime = timezone.now()
    filter_type = request.GET.get('filter', 'all')
    search_query = request.GET.get('search', '')

    # icos_list = ICOEntity.objects.all()
    # Filter based on the selected option
    if filter_type == 'not_verified':
        icos_list = ICOEntity.objects.filter(
            isVerified=False,
            is_rejected=False,
            closes_on__gte=current_datetime,
        )
    elif filter_type == 'defaulter':
        icos_list = ICOEntity.objects.filter(
            isVerified=True,
            is_return_provided = False,
            return_date__lte = current_datetime - timedelta(days=10),
        )
    else:
        icos_list = ICOEntity.objects.all()

     # Apply search filter if search_query is present
    if search_query:
        icos_list = icos_list.filter(
            Q(crop__icontains=search_query) | Q(farmer__user__first_name__icontains=search_query)
        )

    items_per_page = 5

    paginator = Paginator(icos_list, items_per_page)
    page = request.GET.get('page')

    try:
        icos = paginator.page(page)
    except PageNotAnInteger:
        # If the page parameter is not an integer, deliver the first page.
        icos = paginator.page(1)
    except EmptyPage:
        # If the page is out of range (e.g., 9999), deliver the last page.
        icos = paginator.page(paginator.num_pages)

    context = {
        'icos': icos,
        'filter_type': filter_type,
    }
    return render(request, 'superuser/show_icos.html', context)

@never_cache
@login_and_user_type_required('S')
def ico_details(request, ico_id):
    ico = ICOEntity.objects.get(pk=ico_id)
    history = FarmerHistory.objects.filter(farmer=ico.farmer)
    form = ICORejectionForm(instance=ico)
    context = {
        'ico': ico,
        'history': history,
        'form': form,
    }
    return render(request, 'superuser/ico_detail.html', context)

@never_cache
@login_and_user_type_required('S')
def approve_ico(request, ico_id):
    ico = get_object_or_404(ICOEntity, pk=ico_id)
    ico.isVerified = True
    ico.save()
    broadcast_newico_email.delay(ico.farmer.user.first_name, ico.crop, ico.capital, ico.closes_on)
    # You can add additional logic or redirection here if needed
    return redirect('superuser:show_icos')

@never_cache
@login_and_user_type_required('S')
def reject_ico(request, ico_id):
    ico = get_object_or_404(ICOEntity, pk=ico_id)
    history = FarmerHistory.objects.filter(farmer=ico.farmer)

    if request.method == 'POST':
        form = ICORejectionForm(request.POST, instance=ico)
        if form.is_valid():
            ico.is_rejected = True
            form.save()
            ico_rejection_email.delay(ico.farmer.user.first_name, ico.farmer.user.email, ico.crop, ico.rejection_reason)
            return redirect('superuser:show_icos')
    else:
        form = ICORejectionForm(instance=ico)

    context = {
                'ico': ico,
                'history': history,
                'form': form,
                'errorModal': True,
                }
    return render(request, 'superuser/ico_detail.html', context)

@never_cache
def force_ico_returns(request, ico_id):
    ico = get_object_or_404(ICOEntity, pk=ico_id)

            
    farmer_balance = ico.farmer.wallet.balance
    total_quantity = ICOTransactions.objects.filter(ico_id=ico_id).aggregate(Sum('quantity'))['quantity__sum']
    
    investor_share = farmer_balance/total_quantity
    
    with transaction.atomic():
        current_datetime = timezone.now()
        investors = ICOTransactions.objects.filter(ico_id=ico_id)
        for investor_transaction in investors:
            shares_bought = investor_transaction.quantity
            transfer_amount = investor_share * shares_bought
            print('investor: ', shares_bought, transfer_amount)
            print('farmer_wallet: ', ico.farmer.wallet.balance)
            print('investor_wallet: ', investor_transaction.investor.wallet.balance)
            print('mail: ', investor_transaction.investor.user.email)
            ico.farmer.wallet.withdraw(transfer_amount)
            investor_transaction.investor.wallet.deposit(transfer_amount)
            investment_amount = shares_bought*investor_transaction.per_entity_cost
            investor_forced_return_email.delay(investor_transaction.investor.user.first_name, investor_transaction.investor.user.email, transfer_amount, ico.crop, ico.farmer.user.first_name, investment_amount)
        
        ico.return_date = current_datetime
        ico.is_return_provided = True
        ico.save()
        # Create an entry in FarmerHistory
        season = "Rabi" if current_datetime.month in [11, 12, 1, 2] else "Kharif"
        year = current_datetime.year
        # add a entry to farmer history
        FarmerHistory.objects.create(
            farmer=ico.farmer,
            season=season,
            year=year,
            crop=ico.crop,
            area_cultivated=ico.land_area,
            revenue=farmer_balance,
            expenses=ico.capital
        )
    
    redirect_url = reverse('superuser:ico_details', kwargs={'ico_id': ico_id})
    return redirect(redirect_url)

# Farmer Related View here
@never_cache
@login_and_user_type_required('S')
def show_farmers(request):
    filter_type = request.GET.get('filter', 'all')
    search_query = request.GET.get('search', '')

    farmers = Farmer.objects.all()
    # Filter based on the selected option
    if filter_type == 'not_verified':
        farmers = Farmer.objects.filter(
            is_verified=False,
            is_rejected=False,
        )

     # Apply search filter if search_query is present
    if search_query:
        farmers = farmers.filter(
            Q(user__first_name__icontains=search_query) | Q(user__last_name__icontains=search_query) | Q(user__username__icontains=search_query)
        )

    items_per_page = 5

    paginator = Paginator(farmers, items_per_page)
    page = request.GET.get('page')

    try:
        farmers = paginator.page(page)
    except PageNotAnInteger:
        # If the page parameter is not an integer, deliver the first page.
        farmers = paginator.page(1)
    except EmptyPage:
        # If the page is out of range (e.g., 9999), deliver the last page.
        farmers = paginator.page(paginator.num_pages)
    
    context = {
        'farmers': farmers,
        'filter_type': filter_type,
    }
    return render(request, 'superuser/show_farmers.html', context)

@never_cache
@login_and_user_type_required('S')
def farmer_details(request, user_id):
    farmer = Farmer.objects.get(user__pk=user_id)
    history = FarmerHistory.objects.filter(farmer=farmer)
    form = FarmerRejectionForm(instance=farmer)
    context = {
        'farmer': farmer,
        'history': history,
        'form': form,
    }
    return render(request, 'superuser/farmer_detail.html', context)

@never_cache
@login_and_user_type_required('S')
def approve_farmer(request, user_id):
    farmer = Farmer.objects.get(user__pk=user_id)
    farmer.is_verified = True
    farmer.save()
    # print('came here', farmer.is_verified)
    # You can add additional logic or redirection here if needed
    farmer_verified_email.delay(farmer.user.first_name, farmer.user.email)
    return redirect('superuser:show_farmers')

@never_cache
@login_and_user_type_required('S')
def reject_farmer(request, user_id):
    farmer = Farmer.objects.get(user__pk=user_id)
    history = FarmerHistory.objects.filter(farmer=farmer)

    if request.method == 'POST':
        form = FarmerRejectionForm(request.POST, instance=farmer)
        if form.is_valid():
            farmer.is_rejected = True
            form.save()
            farmer_rejection_email.delay(farmer.user.first_name, farmer.user.email, farmer.rejection_reason)
            return redirect('superuser:show_farmers')
    else:
        form = FarmerRejectionForm(instance=farmer)

    context = {
                'farmer': farmer,
                'history': history,
                'form': form,
                'errorModal': True,
                }
    return render(request, 'superuser/farmer_detail.html', context)


# Investor Related View here
@never_cache
@login_and_user_type_required('S')
def show_investors(request):
    filter_type = request.GET.get('filter', 'all')
    search_query = request.GET.get('search', '')

    investors = Investor.objects.all()
    # Filter based on the selected option
    if filter_type == 'not_verified':
        investors = Investor.objects.filter(
            is_verified=False,
            is_rejected=False,

djangopoc/superuser/templates/superuser/farmer_detail.html
{% extends "base_superuser.html" %}
{% block content %}
  <div class="container mt-3 p-2 mb-2 rounded shadow-lg text-center fixed-length">

    <h2>Farmer Details</h2>
    <div class="row">
        <div class="col-md-6">
            <p><strong>Name:</strong> {{ farmer.user.first_name }}</p>
            <p><strong>UserName:</strong> {{ farmer.user.username }}</p>
            <p><strong>Land Area:</strong> {{ farmer.land_area|floatformat:2 }} sq. meters</p>
        </div>
        <div class="col-md-6">
            <p><strong>Aadhar No:</strong> {{ farmer.aadhar_number }}</p>
            <p><strong>PAN No:</strong> {{ farmer.pan_number }}</p>
            <p><strong>Documents:</strong> <a href="{{ farmer.documents.url }}" target="_blank">view documents</a></p>
        </div>
    </div>

    {% if history %}
    <div class="row mt-3">
        <h4>{{ farmer.user.first_name }}'s Farming History</h4>
        <div class="col-md-8 mx-auto">
            <table class="table table-bordered">
                <thead>
                    <tr style="background-color: rgb(255, 226, 9)">
                        <th>Season</th>
                        <th>Year</th>
                        <th>Crop</th>
                        <th>Area Cultivated(sq. meters)</th>
                        <th>Revenue(&#8377;)</th>
                        <th>Expenses(&#8377;)</th>
                        <th>Profit/Loss(%)</th>
                    </tr>
                </thead>
                <tbody>
                    {% for history_entry in history %}
                        <tr>
                            <td>{{ history_entry.season }}</td>
                            <td>{{ history_entry.year }}</td>
                            <td>{{ history_entry.crop }}</td>
                            <td>{{ history_entry.area_cultivated }}</td>
                            <td>{{ history_entry.revenue }}</td>
                            <td>{{ history_entry.expenses }}</td>
                            {% if history_entry.revenue > history_entry.expenses %}
                                <td style="background-color: rgb(121, 222, 121)">
                                    {{ history_entry.percentage|floatformat:2 }}
                                </td>
                            {% else %}
                                <td style="background-color: rgb(239, 91, 91)">
                                    {{ history_entry.percentage|floatformat:2 }}
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endif %}

    {% if farmer.is_verified == False and farmer.is_rejected == False %}
    <div class="row mt-3">
        <div class="col-md-4 mx-auto">
            <a class="btn btn-success btn-block" href="{% url 'superuser:approve_farmer' farmer.user.id %}">Approve Farmer</a>
        </div>
        <div class="col-md-4 mx-auto">
            <button class="btn btn-danger btn-block" data-toggle="modal" data-target="#myModal">Reject Farmer</button>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="myModalLabel">Reject Farmer</h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <!-- Your form goes here -->
                    <form method="post" action="{% url 'superuser:reject_farmer' farmer.user.id %}">
                        {% csrf_token %}
                        <!-- Add your form fields here -->
                        {{ form.as_p }}
                        <!-- Add more form fields as needed -->
                        <button type="submit" class="btn btn-success mt-3">Reject Farmer</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

  </div>
{% endblock %}

djangopoc/superuser/templates/superuser/ico_detail.html
{% extends "base_superuser.html" %}
{% block content %}
  <div class="container mt-3 p-2 rounded shadow-lg text-center fixed-length">

    <h2>ICO Details</h2>

    <div class="row">
        <div class="col-md-6">
            <p><strong>Crop:</strong> {{ ico.crop }}</p>
            <p><strong>Land Area:</strong> {{ ico.land_area }} sq. meters</p>
            <p><strong>Capital:</strong> {{ ico.capital|floatformat:2 }} Rs</p>
            <p><strong>Price:</strong> {{ ico.price|floatformat:2 }}</p>
        </div>
        <div class="col-md-6">
            <p><strong>Quantity:</strong> {{ ico.quantity }}</p>
            <p><strong>Created At:</strong> {{ ico.created_at|date:"Y-m-d" }}</p>
            <p><strong>Closes On:</strong> {{ ico.closes_on|date:"Y-m-d" }}</p>
            <p><strong>Return Date:</strong> {{ ico.return_date|date:"Y-m-d" }}</p>
        </div>
    </div>

    <h4>Farmer Details</h4>
    <div class="row">
        <div class="col-md-6">
            <p><strong>Name:</strong> {{ ico.farmer.user.first_name }}</p>
            <p><strong>UserName:</strong> {{ ico.farmer.user.username }}</p>
            <p><strong>Land Area:</strong> {{ ico.farmer.land_area }} sq. meters</p>
        </div>
        <div class="col-md-6">
            <p><strong>Aadhar No:</strong> {{ ico.farmer.aadhar_number }}</p>
            <p><strong>PAN No:</strong> {{ ico.farmer.pan_number }}</p>
            <p><strong>Documents:</strong> <a href="{{ ico.farmer.documents.url }}" target="_blank">view documents</a></p>
        </div>
    </div>

    {% if history %}
    <div class="row mt-3">
        <h4>{{ ico.farmer.user.first_name }}'s Farming History</h4>
        <div class="col-md-8 mx-auto">
            <table class="table table-bordered">
                <thead>
                    <tr style="background-color: rgb(255, 226, 9)">
                        <th>Season</th>
                        <th>Year</th>
                        <th>Crop</th>
                        <th>Area Cultivated(sq. meters)</th>
                        <th>Revenue(&#8377;)</th>
                        <th>Expenses(&#8377;)</th>
                        <th>Profit/Loss(%)</th>
                    </tr>
                </thead>
                <tbody>
                    {% for history_entry in history %}
                        <tr>
                            <td>{{ history_entry.season }}</td>
                            <td>{{ history_entry.year }}</td>
                            <td>{{ history_entry.crop }}</td>
                            <td>{{ history_entry.area_cultivated }}</td>
                            <td>{{ history_entry.revenue }}</td>
                            <td>{{ history_entry.expenses }}</td>
                            {% if history_entry.revenue > history_entry.expenses %}
                                <td style="background-color: rgb(121, 222, 121)">
                                    {{ history_entry.percentage|floatformat:2 }}
                                </td>
                            {% else %}
                                <td style="background-color: rgb(239, 91, 91)">
                                    {{ history_entry.percentage|floatformat:2 }}
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endif %}

    {% if ico.isVerified == False and ico.is_rejected == False %}
    <div class="row mt-3">
        <div class="col-md-4 mx-auto">
            <a class="btn btn-success btn-block" href="{% url 'superuser:approve_ico' ico.id %}">Approve ICO</a>
        </div>
        <div class="col-md-4 mx-auto">
            <button class="btn btn-danger btn-block" data-toggle="modal" data-target="#myModal">Reject ICO</button>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="myModalLabel">Reject ICO</h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <!-- Your form goes here -->
                    <form method="post" action="{% url 'superuser:reject_ico' ico.id %}">
                        {% csrf_token %}
                        <!-- Add your form fields here -->
                        {{ form.as_p }}
                        <!-- Add more form fields as needed -->
                        <!-- <div id="form-errors"></div> -->
                        <button type="submit" class="btn btn-success mt-3">Reject ICO</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    {% if ico.is_remaining %}
    <div class="text-center">
        <a href="{% url 'superuser:force_ico_returns' ico.id %}" class="btn btn-warning mt-1">Force Transfer</a>
    </div>
    {% endif %}

  </div>

{% endblock %}

djangopoc/superuser/templates/superuser/investor_detail.html
{% extends "base_superuser.html" %}
{% block content %}
  <div class="container mt-3 p-2 mb-2 rounded shadow-lg text-center fixed-length">

    <h2>Investor Details</h2>
    <div class="row">
        <div class="col-md-6">
            <p><strong>Name:</strong> {{ investor.user.first_name }}</p>
            <p><strong>UserName:</strong> {{ investor.user.username }}</p>
            <p><strong>Email:</strong> {{ investor.user.email }}</p>
            <p><strong>Documents:</strong> <a href="{{ investor.documents.url }}" target="_blank">view documents</a></p>
        </div>
        <div class="col-md-6">
            <p><strong>Aadhar No:</strong> {{ investor.aadhar_number }}</p>
            <p><strong>PAN No:</strong> {{ investor.pan_number }}</p>
            <p><strong>Contact No:</strong> {{ investor.user.phone }}</p>
        </div>
    </div>

    {% if investor.is_verified == False and investor.is_rejected == False %}
    <div class="row mt-3">
        <div class="col-md-4 mx-auto">
            <a class="btn btn-success btn-block" href="{% url 'superuser:approve_investor' investor.user.id %}">Approve Investor</a>
        </div>
        <div class="col-md-4 mx-auto">
            <button class="btn btn-danger btn-block" data-toggle="modal" data-target="#myModal">Reject Investor</button>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="myModalLabel">Reject Investor</h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <!-- Your form goes here -->
                    <form method="post" action="{% url 'superuser:reject_investor' investor.user.id %}">
                        {% csrf_token %}
                        <!-- Add your form fields here -->
                        {{ form.as_p }}
                        <!-- Add more form fields as needed -->
                        <button type="submit" class="btn btn-success mt-3">Reject Investor</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

  </div>
{% endblock %}

djangopoc/superuser/templates/superuser/show_investors.html
{% extends "base_superuser.html" %}
{% block content %}
  <div class="container mt-3">
    <form method="get" action="{% url 'superuser:show_investors' %}" class="mb-4">
        <div class="row">
          <div class="col-md-8">
            <!-- <label for="filter" class="form-label">Filter by:</label> -->
            <select name="filter" id="filter" class="form-select">
                <option value="all" {% if filter_type == 'all' %}selected{% endif %}>All</option>
                <option value="not_verified" {% if filter_type == 'not_verified' %}selected{% endif %}>For Verification</option>
            </select>
          </div>
          <div class="col-md-4">
            <button type="submit" class="btn btn-secondary">Apply Filter</button>
          </div>
        </div>
      </form>
    {% if investors %}
    {% for investor in investors %}
      <div class="card mb-4">
        <div class="row">
            <div class="col-md-4">
                <img src="https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aW52ZXN0b3JzfGVufDB8fDB8fHww" class="card-img-top" alt="crop" style="width: px; height: 200px; object-fit: cover;">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h4 class="card-title">{{ investor.user.first_name }}</h4>
                    <div class="row">
                        <div class="col-md-6 card-text">
                            <strong>Aadhar No: </strong>{{ investor.aadhar_number }}<br>
                            <strong>PAN No: </strong>{{ investor.pan_number }}<br> 
                            <strong>Email: </strong>{{ investor.user.email }}
                        </div>
                        <div class="col-md-6 card-text">
                            <strong>UserName: </strong>{{ investor.user.username }}<br>
                            <strong>Contact: </strong>{{ investor.user.phone }}
                        </div>
                    </div>
                    <!-- <a href="#" class="btn btn-primary mt-3">Show Details</a> -->
                    <!-- Pass the ICO details directly to the details template using the URL -->
                    <div class="row">
                        <div class="col-md-6"><a href="{% url 'superuser:investor_details' investor.user.id %}" class="btn btn-success mt-3">Show Details</a></div>
                        {% if investor.is_verified == False and investor.is_rejected == False %}
                            <div class="col-md-6"><a href="{% url 'superuser:approve_investor' investor.user.id %}" class="btn btn-warning mt-3">Approve Investor</a></div>
                        {% endif %}
                    </div>
                </div>
            </div>
    </div>
    </div>
    {% endfor %}
    <!-- Pagination links -->
    <div class="pagination mt-3" style="justify-content: center;">
        <span class="step-links">
            {% if investors.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ investors.previous_page_number }}">previous</a>
            {% endif %}
        
            <span class="current">
                Page {{ investors.number }} of {{ investors.paginator.num_pages }}.
            </span>
        
            {% if investors.has_next %}
                <a href="?page={{ investors.next_page_number }}">next</a>
                <a href="?page={{ investors.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% else %}
        <div class="alert alert-info mt-3 text-center" role="alert">
            There are No Investors present for Approval!
        </div>
    {% endif %}
  </div>
{% endblock %}

djangopoc/superuser/templates/superuser/superuser_profile.html
{% extends "base_superuser.html" %}
{% block content %}
  <div class="container mt-5 rounded shadow-lg text-center fixed-length">

    <div class="row mt-3">
        <div class="col-md-6 mx-auto card shadow-lg">
            <h1 class="text-center">{{ user.first_name|capfirst }} {{ user.last_name|capfirst }}</h1>
            <p class="text-center"><b>UserName:</b> {{ user.username }}</p>
            <p class="text-center"><b>Email:</b> {{ user.email }}</p>
            <p class="text-center"><b>Contact No:</b> {{ user.phone }}</p>
            <!-- <a href="http://127.0.0.1:8000/admin/">Full Acess</a> -->
        </div>
    </div>

</div>

{% endblock %}